CREATE TABLE `bd_data` (
  `ids` int(11) NOT NULL AUTO_INCREMENT,
  `filename` varchar(50) NOT NULL,
  `filetime` datetime NOT NULL,
  `filesave` json DEFAULT NULL,
  `imei1` varchar(16) NOT NULL,
  `imei2` varchar(16) DEFAULT NULL,
  `productname` varchar(30) NOT NULL,
  `idcard` varchar(30) DEFAULT NULL,
  `perso_system` varchar(30) DEFAULT NULL,
  `bt_mac` varchar(20) DEFAULT NULL,
  `wifi_mac` varchar(20) DEFAULT NULL,
  `commercial_ref` varchar(20) DEFAULT '',
  `launcher_time_lk` json DEFAULT NULL,
  `launcher_time_la` json DEFAULT NULL,
  `boot_reason` json DEFAULT NULL,
  `fec_record` varchar(70) DEFAULT '',
  `lifetime` int(11) DEFAULT NULL,
  `productmodel` varchar(20) DEFAULT '',
  `used_time` varchar(20) DEFAULT '',
  `sim_time` varchar(20) DEFAULT '',
  `wifi_time` varchar(20) DEFAULT '',
  `pcba_sn` varchar(20) DEFAULT '',
  `mini_ver` varchar(20) DEFAULT '',
  `bt_addr` varchar(20) DEFAULT '',
  `wifi_addr` varchar(20) DEFAULT NULL,
  `system_ver` varchar(20) DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `rooted` varchar(10) DEFAULT NULL,
  `battery_v` int(11) DEFAULT NULL,
  `tool` varchar(50) DEFAULT NULL,
  `loginfo` varchar(100) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `parser_mail` varchar(50) DEFAULT NULL,
  `parser_text` mediumtext,
  `parser_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `parser_history` mediumtext,
  `parser_step` int(11) DEFAULT NULL,
  PRIMARY KEY (`ids`),
  UNIQUE KEY `ids_UNIQUE` (`ids`),
  UNIQUE KEY `filename_UNIQUE` (`filename`)
) ENGINE=MyISAM AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;
